services:
  web:
    image: php:8.0-apache
    container_name: school_web
    ports:
      - "8080:80"
    volumes:
      - ./school_php/public:/var/www/html
      - ./school_php/src:/var/www/src
    depends_on:
      - db

  db:
    image: mysql:8.0.18
    container_name: school_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: GOHANNODENDO
      MYSQL_USER: web2511
      MYSQL_PASSWORD: web2511
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Asia/Tokyo
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
